[package]
name = "cargo_hello_word"
version = "0.1.0"
authors = ["jaime andrade <jaimeandrade454@gmail.com>"]
edition = "2018"

[dependencies]
regex = "0.2"
reqwest = "0.10.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0.104"


